- project:
    name: software-factory/firehooks
    check:
      jobs:
        - sf-rpm-build
        - tox-py36:
            nodeset: fedora-latest-runc
        - tox-py35:
            nodeset:
              nodes:
                - name: testrunner
                  label: runc-fedora
            voting: false
        - linters
    gate:
      jobs:
        - tox-py36:
            nodeset: fedora-latest-runc
        - linters
        - tox-py35:
            nodeset:
              nodes:
                - name: testrunner
                  label: runc-fedora
            voting: false
        - wait-for-changes-ahead:
            dependencies:
              - sf-rpm-build
              - tox-py36
              - linters
        - sf-rpm-publish:
            dependencies:
              - wait-for-changes-ahead
