logging:
  level: DEBUG
broker:
  url: sftests.com
  port: 1883

software-factory:
  auth:
    user: SF_SERVICE_USER
    password: password
  url: https://sftests.com
  managesf: http://managesf.sftests.com:20001
  gerrit: http://managesf.sftests.com:8000/r/a/

# Hooks configuration
hooks:
  SFTaigaIO:
      # project is a python regular expression to apply on the project field of a change
    - project: myCoolProject|myOtherCoolProject
      auth:
        username: taigabot
        password: XXX
      taiga_project: my_cool_project
  # Actually no config needed here yet
  SFZuul:
    - {}
